# Generated by Django 5.0.6 on 2024-11-11 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('re_id', models.AutoField(primary_key=True, serialize=False)),
                ('re_date', models.DateTimeField(auto_now_add=True)),
                ('re_name', models.CharField(max_length=127)),
                ('re_email', models.EmailField(max_length=127)),
                ('re_birth', models.DateField()),
                ('re_password', models.CharField(max_length=63)),
                ('re_status', models.CharField(choices=[('on', 'Online'), ('off', 'Offline'), ('del', 'Apagado')], default='on', max_length=10)),
            ],
        ),
    ]
